version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=event_manager
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:7.3
    environment:
      - PGADMIN_DEFAULT_EMAIL=jmdm@coordinadora.com.co
      - PGADMIN_DEFAULT_PASSWORD=coordinadora
    ports:
      - "5050:80"
    depends_on:
      - postgres

  event_manager:
    build: .
    ports:
      - "8000-8004:3000"
    links:
      - "postgres:event_manager"
    deploy:
      mode: replicated
      replicas: 5
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 60s
